<?php
// This file is part of PowerEduc - https://powereduc.org/
//
// PowerEduc is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PowerEduc is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PowerEduc.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for PowerEduc installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.powereduc.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('POWEREDUC_INTERNAL') || die();

$string['clianswerno'] = 'ei';
$string['cliansweryes'] = 'jah';
$string['cliincorrectvalueerror'] = 'Tõrge, „{$a->option}“ sobimatu väärtus „{$a->value}“';
$string['cliincorrectvalueretry'] = 'Sobimatu väärtus, proovige uuesti';
$string['clitypevalue'] = 'tüübi väärtus';
$string['clitypevaluedefault'] = 'tüübi väärtus, vaikeväärtuse kasutamiseks vajutage sisestusklahvi ({$a})';
$string['cliunknowoption'] = 'Tundmatud valikud:
  {$a}
Kasutage spikrivalikut.';
$string['cliyesnoprompt'] = 'tippige y (jah) või n (ei)';
$string['environmentrequireinstall'] = 'peab olema installitud ja lubatud';
$string['environmentrequireversion'] = 'nõutav on versioon {$a->needed}, teil töötab versioon {$a->current}';
$string['upgradekeyset'] = 'Versioonitäienduse võti (jätke tühjaks, kui te ei soovi seda määrata)';
